global:
  labels:
    app: api-requester
    env: testing

cronJob:
  schedule: "* * * * *"
  ttlSecondsAfterFinished: 300
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi
  env:
    apiURL: "https://gutendex.com/books"

storageClass:
  provisioner: "k8s.io/minikube-hostpath"

volume:
  requests:
    storage: "5Gi"

  
