apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-requester-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: api-requester
            image: tfvoncan/api_requester:latest
            imagePullPolicy: Always
            volumeMounts:
            - name: api-data
              mountPath: /api-data
          volumes:
            - name: api-data
              persistentVolumeClaim:
                claimName: api-data-pvc
          restartPolicy: OnFailure
