apiVersion: batch/v1
kind: CronJob
metadata:
  name: apiRequesterJob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: api-requester
            image: api-requester:latest
            command: ["/bin/bash"]
            args: ["-c", "python api-requester.py"]
            imagePullPolicy: Never # This is only for the local implementation. You will need to push the image to a repo and pull it down by changing this to Always or IfNotPresent
          volumeMounts:
            - name: api-data
              mountPath: /data
          volumes:
            - name: api-data
              persistentVolumeClaim:
                claimName: api-data-pvc
          restartPolicy: OnFailure
