apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minikube-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath #This provisioner will only work with minikube. If you are using another local k8s solution you will need to change this
reclaimPolicy: Retain 
allowVolumeExpansion: true
volumeBindingMode: Immediate
