apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data-pvc
spec:
  storageClassName: minikube-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-data-pv
spec:
  storageClassName: minkube-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
