apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - image: busybox
    name: pvc-inspector
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: /api-data
      name: api-data
  volumes:
  - name: api-data
    persistentVolumeClaim:
      claimName: api-data-pvc
